/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#0d0096",
        "outline-variant": "#464554",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#703700",
        "surface-container": "#1f1f23",
        "secondary": "#c0c1ff",
        "on-tertiary-fixed": "#301400",
        "on-secondary": "#292a60",
        "surface-container-lowest": "#0e0e12",
        "surface-tint": "#c0c1ff",
        "surface-container-high": "#2a292e",
        "on-surface": "#e4e1e7",
        "surface-container-low": "#1b1b1f",
        "tertiary-container": "#d97721",
        "secondary-fixed-dim": "#c0c1ff",
        "inverse-on-surface": "#303034",
        "surface": "#131317",
        "surface-dim": "#131317",
        "outline": "#908fa0",
        "surface-variant": "#353439",
        "tertiary-fixed": "#ffdcc5",
        "on-secondary-fixed": "#13144a",
        "tertiary-fixed-dim": "#ffb783",
        "inverse-surface": "#e4e1e7",
        "on-error": "#690005",
        "primary": "#c0c1ff",
        "error-container": "#93000a",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "on-secondary-fixed-variant": "#404178",
        "on-primary": "#1000a9",
        "on-secondary-container": "#b2b3f2",
        "inverse-primary": "#494bd6",
        "on-tertiary": "#4f2500",
        "secondary-container": "#42447b",
        "primary-fixed": "#e1e0ff",
        "surface-bright": "#39393d",
        "tertiary": "#ffb783",
        "on-tertiary-container": "#452000",
        "on-background": "#e4e1e7",
        "background": "#131317",
        "error": "#ffb4ab",
        "on-surface-variant": "#c7c4d7",
        "on-primary-fixed-variant": "#2f2ebe",
        "primary-container": "#8083ff",
        "secondary-fixed": "#e1e0ff",
        "surface-container-highest": "#353439"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "1rem",
        "full": "9999px"
      }
    },
  },
  plugins: [],
};