/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#0040a1",
        "on-surface": "#191b23",
        "on-secondary-fixed": "#0d1c2e",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f0f0fb",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-highest": "#e1e2ec",
        "on-primary-container": "#ccd8ff",
        "secondary": "#515f74",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-dim": "#d9d9e4",
        "inverse-surface": "#2e3038",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "surface-container-high": "#e7e7f2",
        "primary-fixed-dim": "#b2c5ff",
        "on-background": "#191b23",
        "on-tertiary-container": "#ffd29e",
        "on-primary-fixed": "#001847",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#d5e3fc",
        "primary-fixed": "#dae2ff",
        "tertiary-fixed": "#ffddb8",
        "on-secondary-fixed-variant": "#3a485b",
        "inverse-primary": "#b2c5ff",
        "surface": "#faf8ff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container": "#ededf8",
        "surface-variant": "#e1e2ec",
        "on-primary": "#ffffff",
        "surface-container-low": "#f2f3fe",
        "background": "#faf8ff",
        "primary": "#0040a1",
        "outline-variant": "#c3c6d6",
        "on-secondary-container": "#57657a",
        "outline": "#737785",
        "surface-tint": "#0056d2",
        "on-surface-variant": "#424654",
        "tertiary-container": "#865400",
        "primary-container": "#0056d2",
        "secondary-fixed-dim": "#b9c7df",
        "secondary-container": "#d5e3fc",
        "surface-bright": "#faf8ff",
        "on-secondary": "#ffffff",
        "tertiary": "#663f00"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      }
    },
  },
  plugins: [],
};