spring.datasource.url=jdbc:mysql://localhost:3306/jobtrackr
spring.datasource.username=root
spring.datasource.password=fasoyin05$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.security.filter.order=10
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=am9idHJhY2tyX3N1cGVyX3NlY3JldF9rZXlfY2hhbmdlX2luX3Byb2R1Y3Rpb25fMjAyNA==
jwt.expiration=86400000

server.port=8080